### ISSUE TITLE
more than one user on same IP

### ISSUE THREAD

**Issue by Samuel-Bie** [awssat/laravel-visits#35] opened 2019-12-15 12:14 UTC
First of all congratulate the creators of this solution.

But there is a question. The viewcount is not doubling as the page reloads, that's fine, now I've experimented with 2 different browsers and it hasn't increased the count, assuming I'm in my development environment.

In this context, assuming my users will be on the internet, some of them may be using shared (public) IPs, in which case there is a possibility of giving me a wrong number of views.

**Comment by abdumu** [comment] 2019-12-15 16:30
Hello, 

Thanks for using the package.

- You can always use `forceIncrement` instead of `increment` to bypass IP limits,  or you can change the `remember_ip` in config/visit.php to zero! 

- In case of shared IPs we as developers usually use cookies, and that is not included with the package as it is the developer choice. 
you can (I'm just suggesting here, you can use any method to solve this) add a condition to your code as 
```if(... check cookies ...) {
    forceIncrement(...);
   set cookies ...
}```


I'm closing the issue since it's not a bug.

**Closed by abdumu** 2019-12-15 16:30 UTC
